# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddNewPhase.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 339)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEditPhase = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditPhase.setGeometry(QtCore.QRect(20, 50, 231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEditPhase.setFont(font)
        self.plainTextEditPhase.setObjectName("plainTextEditPhase")
        self.plainTextEditMeaning = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditMeaning.setGeometry(QtCore.QRect(290, 50, 361, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEditMeaning.setFont(font)
        self.plainTextEditMeaning.setObjectName("plainTextEditMeaning")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 16, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 15, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButtonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(230, 180, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.labelResponse = QtWidgets.QLabel(self.centralwidget)
        self.labelResponse.setGeometry(QtCore.QRect(30, 269, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelResponse.setFont(font)
        self.labelResponse.setText("")
        self.labelResponse.setObjectName("labelResponse")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Phase"))
        self.label_2.setText(_translate("MainWindow", "Meaning"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))
